<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AnimalClassifier.Infrastructure\AnimalClassifier.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.Extensions.ML" />
    <PackageReference Include="Microsoft.ML" />
    <PackageReference Include="Microsoft.ML.ImageAnalytics" />
    <PackageReference Include="Microsoft.ML.TensorFlow" />
    <PackageReference Include="OpenCvSharp4" />
    <PackageReference Include="OpenCvSharp4.runtime.win" />
    <PackageReference Include="SciSharp.TensorFlow.Redist" />
  </ItemGroup>

</Project>
